[project]
name = "kons1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.7"
dependencies = [
    "evolution",
]

[tool.uv.sources]
evolution = { git = "https://github.com/LuisFoerster/evolution.git", rev = "main" }

